services:
    app:
        build: .
        env_file:
            - .env
        extra_hosts:
            - 'host.build.internal:host-gateway'
        ports:
            - '8001:80'
        volumes:
            - '.:/app'
            - './build/entrypoints/docker-entrypoint-prd.sh:/entrypoint.sh'
        networks:
            - bubble
        depends_on:
            - mysql
        entrypoint: ["/bin/sh", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - bubble
networks:
    bubble:
        driver: bridge
