name: Teste de Qualidade de código na PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: "Testes Unitários"
    runs-on: ubuntu-latest
    env:
      APP_KEY: base64:IWljo6O5J1iYUToQox1ZaAXLjikeQTDCl+RwxEJx/8k=
    steps:
      - name: "Checkout do projeto"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: swoole

      - name: "Instalação das dependencias"
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

      - name: "Execução dos testes unitários"
        run: vendor/bin/phpunit
